core/urls.py
from django.urls import path

from . import views, htmx_views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('post/', views.PostView.as_view(), name='post'),
]

htmx_urlpatterns = [
    path('render-navbar/', htmx_views.render_navbar, name='render-navbar'),
]

urlpatterns += htmx_urlpatterns

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views, htmx_views

app_name = 'user'


urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

htmx_urlpatterns = [
    path('check-username/', htmx_views.check_username, name='check-username'),
]

urlpatterns += htmx_urlpatterns

core/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

user/forms.py
from django import forms
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import User


class SignInForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        required=True
    )
    password = forms.CharField(widget=forms.PasswordInput())


class SignUpForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['username', ]:
            self.fields[fieldname].help_text = None
        self.helper = FormHelper(self)
        self.helper.form_id = 'register-form'
        self.helper.attrs = {
            'hx-post': reverse_lazy('user:register'),
            'hx-target': '#register-form',
            'hx-swap': 'outerHTML'
        }
        self.helper.add_input(Submit('submit', 'Register'))

    password = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput(
                attrs={'placeholder': 'password'}
            )
        )
    confirm_password = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput(
                attrs={'placeholder': 'repeat password'}
            )
        )
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password',
            'confirm_password'
        )
        widgets = {
            'username': forms.TextInput(attrs={
                'hx-get': reverse_lazy('user:check-username'),
                'hx-target': '#div_id_username',
                'hx-trigger': 'keyup[target.value.length > 3]'
            }),
        }
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) <= 3:
            raise forms.ValidationError("Username is too short")
        return username


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            self.add_error(
                "password",
                forms.ValidationError(
                    "Passwords didn't matched!"
                )
            )
            self.add_error(
                "confirm_password",
                forms.ValidationError(
                "Passwords didn't matched!"))
        return cleaned_data

    def save(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        return User.objects.create_user(
            username=username,
            email=email,
            password=password
        )

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'base.html'


class BlogView(TemplateView):
    template_name = 'blog.html'


class PostView(TemplateView):
    template_name = 'post.html'

user/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView
from django.template.context_processors import csrf
from crispy_forms.utils import render_crispy_form
from crispy_forms.templatetags.crispy_forms_filters import as_crispy_field
from django.http import HttpResponse
from django.utils.safestring import mark_safe

from .forms import SignInForm, SignUpForm


class Login(View):
    def post(self, request, *args, **kwargs):
        form = SignInForm(request.POST)
        if request.htmx:
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    message = mark_safe("""<button class="toastMessage d-none" name="success">Successfully Logged In!</button>""")
                    template = render(request, 'navbar.html', {'message': message, 'user': user})
                    template['HX-History-Restore-Request'] = True
                    return template
                else:
                    message = mark_safe("""<button class="toastMessage d-none" name="error">Invalid Username or Password!</button>""")
                    return render(request, 'navbar.html', {'message': message, 'form': form})
        else:
            return redirect('core:home')
    
    def get(self, request, *args, **kwrgs):
        form = SignInForm()
        if request.htmx:
            template = render(request, 'user/fragments/login.html', {'form': form})
            return template
        else:
            return redirect('core:home')


class Logout(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.htmx:
            logout(request)
            message = mark_safe("""<button class="toastMessage d-none" name="info">You are Logged Out!</button>""")
            return render(request, 'navbar.html', {'message': message, 'user': None})


class RegisterView(FormView):
    form_class = SignUpForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('core:home')
    success_message = 'User registered successfully!'

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            template = render(request, 'index.html')
            template['Hx-Push'] = '/'
            return template

        ctx = {}
        ctx.update(csrf(request))
        form_html = render_crispy_form(form, context=ctx)
        return HttpResponse(form_html)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="all,follow" />
    <!-- Bootstrap CSS-->
    <link
      rel="stylesheet"
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!-- Font Awesome CSS-->
    <link
      rel="stylesheet"
      href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}"
    />
    <!-- Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}" />
    <!-- Google fonts - Open Sans-->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700"
    />
    <!-- Fancybox-->
    <link
      rel="stylesheet"
      href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}"
    />
    <!-- theme stylesheet-->
    <link
      rel="stylesheet"
      href="{% static 'css/style.red.css' %}"
      id="theme-stylesheet' %}"
    />
    <!-- Toastr -->
    <link rel="stylesheet" href="{% static 'vendor/toastr/css/toastr.min.css' %}" />
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    
  </head>
  <body>
    
    <div id="navbars">
      {% include './navbar.html' %}
    </div>
    
    <div id="root">
      {% block content %}
        {% include './index.html' %}
      {% endblock %}
    </div>
    
    {% include './footer.html' %}

    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'vendor/toastr/js/toastr.min.js' %}"></script>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/blog.html
{% extends './base.html' %}

{% load static %}

{% block title %}Blog{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <!-- Latest Posts -->
      <main class="posts-listing col-lg-8"> 
        <div class="container">
          <div class="row">
            <!-- post -->
            <div class="post col-xl-6">
              <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-post-1.jpeg' %}" alt="..." class="img-fluid"></a></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date meta-last">20 May | 2016</div>
                  <div class="category"><a href="#">Business</a></div>
                </div><a href="post.html">
                  <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{% static 'img/avatar-3.jpg' %}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>John Doe</span></div></a>
                  <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>12</div>
                </footer>
              </div>
            </div>
            <!-- post             -->
            <div class="post col-xl-6">
              <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-post-2.jpg' %}" alt="..." class="img-fluid"></a></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date meta-last">20 May | 2016</div>
                  <div class="category"><a href="#">Business</a></div>
                </div><a href="post.html">
                  <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{% static 'img/avatar-2.jpg' %}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>John Doe</span></div></a>
                  <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>12</div>
                </div>
              </div>
            </div>
            <!-- post             -->
            <div class="post col-xl-6">
              <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-post-3.jpeg' %}" alt="..." class="img-fluid"></a></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date meta-last">20 May | 2016</div>
                  <div class="category"><a href="#">Business</a></div>
                </div><a href="post.html">
                  <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{% static 'img/avatar-3.jpg' %}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>John Doe</span></div></a>
                  <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>12</div>
                </div>
              </div>
            </div>
            <!-- post -->
            <div class="post col-xl-6">
              <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-post-4.jpeg' %}" alt="..." class="img-fluid"></a></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date meta-last">20 May | 2016</div>
                  <div class="category"><a href="#">Business</a></div>
                </div><a href="post.html">
                  <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{% static 'img/avatar-1.jpg' %}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>John Doe</span></div></a>
                  <div class="date"><i class="icon-clock"></i> 2 months ago</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>12</div>
                </div>
              </div>
            </div>
          </div>
          <!-- Pagination -->
          <nav aria-label="Page navigation example">
            <ul class="pagination pagination-template d-flex justify-content-center">
              <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
              <li class="page-item"><a href="#" class="page-link active">1</a></li>
              <li class="page-item"><a href="#" class="page-link">2</a></li>
              <li class="page-item"><a href="#" class="page-link">3</a></li>
              <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
            </ul>
          </nav>
        </div>
      </main>
      <aside class="col-lg-4">
        <!-- Widget [Search Bar Widget]-->
        <div class="widget search">
          <header>
            <h3 class="h6">Search the blog</h3>
          </header>
          <form action="#" class="search-form">
            <div class="form-group">
              <input type="search" placeholder="What are you looking for?">
              <button type="submit" class="submit"><i class="icon-search"></i></button>
            </div>
          </form>
        </div>
        <!-- Widget [Latest Posts Widget]        -->
        <div class="widget latest-posts">
          <header>
            <h3 class="h6">Latest Posts</h3>
          </header>
          <div class="blog-posts"><a href="#">
              <div class="item d-flex align-items-center">
                <div class="image"><img src="{% static 'img/small-thumbnail-1.jpg' %}" alt="..." class="img-fluid"></div>
                <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i> 500</div>
                    <div class="comments"><i class="icon-comment"></i>12</div>
                  </div>
                </div>
              </div></a><a href="#">
              <div class="item d-flex align-items-center">
                <div class="image"><img src="{% static 'img/small-thumbnail-2.jpg' %}" alt="..." class="img-fluid"></div>
                <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i> 500</div>
                    <div class="comments"><i class="icon-comment"></i>12</div>
                  </div>
                </div>
              </div></a><a href="#">
              <div class="item d-flex align-items-center">
                <div class="image"><img src="{% static 'img/small-thumbnail-3.jpg' %}" alt="..." class="img-fluid"></div>
                <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i> 500</div>
                    <div class="comments"><i class="icon-comment"></i>12</div>
                  </div>
                </div>
              </div></a></div>
        </div>
        <!-- Widget [Categories Widget]-->
        <div class="widget categories">
          <header>
            <h3 class="h6">Categories</h3>
          </header>
          <div class="item d-flex justify-content-between"><a href="#">Growth</a><span>12</span></div>
          <div class="item d-flex justify-content-between"><a href="#">Local</a><span>25</span></div>
          <div class="item d-flex justify-content-between"><a href="#">Sales</a><span>8</span></div>
          <div class="item d-flex justify-content-between"><a href="#">Tips</a><span>17</span></div>
          <div class="item d-flex justify-content-between"><a href="#">Local</a><span>25</span></div>
        </div>
        <!-- Widget [Tags Cloud Widget]-->
        <div class="widget tags">       
          <header>
            <h3 class="h6">Tags</h3>
          </header>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
            <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
            <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
            <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
            <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
{% endblock content %}

templates/footer.html
{% load static %}

<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h6 class="text-white">Bootstrap Blog</h6>
        </div>
        <div class="contact-details">
          <p>53 Broadway, Broklyn, NY 11249</p>
          <p>Phone: (020) 123 456 789</p>
          <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
          <ul class="social-menu">
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-behance"></i></a>
            </li>
            <li class="list-inline-item">
              <a href="#"><i class="fa fa-pinterest"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="menus d-flex">
          <ul class="list-unstyled">
            <li><a href="#">My Account</a></li>
            <li><a href="#">Add Listing</a></li>
            <li><a href="#">Pricing</a></li>
            <li><a href="#">Privacy &amp; Policy</a></li>
          </ul>
          <ul class="list-unstyled">
            <li><a href="#">Our Partners</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">How It Works</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="latest-posts">
          <a href="#">
            <div class="post d-flex align-items-center">
              <div class="image">
                <img
                  src="{% static 'img/small-thumbnail-1.jpg' %}"
                  alt="..."
                  class="img-fluid"
                />
              </div>
              <div class="title">
                <strong>Hotels for all budgets</strong
                ><span class="date last-meta">October 26, 2016</span>
              </div>
            </div></a
          ><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image">
                <img
                  src="{% static 'img/small-thumbnail-2.jpg' %}"
                  alt="..."
                  class="img-fluid"
                />
              </div>
              <div class="title">
                <strong>Great street atrs in London</strong
                ><span class="date last-meta">October 26, 2016</span>
              </div>
            </div></a
          ><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image">
                <img
                  src="{% static 'img/small-thumbnail-3.jpg' %}"
                  alt="..."
                  class="img-fluid"
                />
              </div>
              <div class="title">
                <strong>Best coffee shops in Sydney</strong
                ><span class="date last-meta">October 26, 2016</span>
              </div>
            </div></a
          >
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2017. All rights reserved. Your great site.</p>
        </div>
        <div class="col-md-6 text-right">
          <p>
            Template By
            <a
              href="https://bootstrapious.com/p/bootstrap-carousel"
              class="text-white"
              >Bootstrapious</a
            >
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/modal.html
{% load crispy_forms_tags %}

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Login</h5>
      </div>
      <div class="modal-body">
            <form hx-post="{% url 'user:login' %}" hx-target="#navbars" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <div class="row">
                    {% if form %}
                        <div class="col-md-12">{{form.username|as_crispy_field}}</div>
                        <div class="col-md-12">{{form.password|as_crispy_field}}</div>
                    {% endif %}
                </div>
                <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">Login</button>
            </form>
        </div>
    </div>
  </div>
</div>

templates/navbar.html
{% include './fragments/message.html' %}

<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand -->
        <a href="{% url 'core:home' %}" class="navbar-brand">BlogSite</a>
        <!-- Toggle Button-->
        <button
          type="button"
          data-toggle="collapse"
          data-target="#navbarcollapse"
          aria-controls="navbarcollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
          class="navbar-toggler"
        >
          <span></span><span></span><span></span>
        </button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'core:home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:blog' %}" class="nav-link">Blog</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:post' %}" class="nav-link">Post</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'core:home' %}" class="nav-link">Admin</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:home' %}" class="nav-link">Profile</a>
          </li>
          <li class="nav-item">
            <a hx-get="{% url 'user:logout' %}" hx-push-url="{% url 'core:home' %}" hx-target="#navbars" class="nav-link">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'user:register' %}" class="nav-link">Register</a>
          </li>
          <li class="nav-item">
            <a hx-get="{% url 'user:login' %}" hx-push-url="true" hx-swap="outerHTML" hx-target="#root" class="nav-link">Login</a>
          </li>
          {% endif %}
        </ul>
        <form class="search-area-input px-2">
          <input class="form-control mr-sm-2" type="search" placeholder="Search..." />
        </form>
      </div>
    </div>
  </nav>
</header>

templates/user/fragments/login.html
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow my-2">
            <div class="row p-3">
                <div class="col-md-12">
                    <h4 class="text-center mt-2">Log In</h4>
                    <hr class="w-25" />
                </div>
                <div class="col-md-12">
                    <form action="{% url 'user:login' %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field|as_crispy_field }}
                        {% endfor %}
                        <button class="btn btn-primary pull-right mb-2" type="submit" hx-post="{% url 'user:login' %}" hx-target="#navbars">Login</button>
                    </form>
                    <div>
                        <p class="text-xs-center">
                            <a href="#">Need a Account?</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include '../../fragments/message.html' %}

templates/user/fragments/modal.html
{% load crispy_forms_tags %}

{% load static %}

<button id="triggerModalForm" type="button" class="btn btn-primary d-none" data-toggle="modal" data-target="#exampleModalCenter">
  Modal Form
</button>

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Login</h5>
      </div>
      <div class="modal-body">
            <form hx-post="{% url 'user:login' %}" hx-target="#navbars" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <div class="row">
                    {% if form %}
                        <div class="col-md-12">{{form.username|as_crispy_field}}</div>
                        <div class="col-md-12">{{form.password|as_crispy_field}}</div>
                    {% endif %}
                </div>
                <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">Login</button>
            </form>
        </div>
    </div>
  </div>
</div>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
  $("#triggerModalForm").trigger('click');
</script>

templates/user/login.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card shadow my-2">
            <div class="row p-3">
                <div class="col-md-12">
                    <h4 class="text-center mt-2">Log In</h4>
                    <hr class="w-25" />
                </div>
                <div class="col-md-12">
                    <form action="{% url 'user:login' %}" metho="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field|as_crispy_field }}
                        {% endfor %}
                        <button class="btn btn-primary pull-right mb-2" type="submit">Login</button>
                    </form>
                    <div>
                        <p class="text-xs-center">
                            <a href="#">Need a Account?</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}